#sky:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/sky_take_out?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
#    username: root
#    password: your_mysql_password

sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: your_mysql_password

  alioss:
    endpoint: your_oss_endpoint
    access-key-id: your_access_key_id
    access-key-secret: your_access_key_secret
    bucket-name: your_bucket_name

  redis:
    host: localhost
    port: 6379
    password: your_redis_password
    database: 10

  wechat:
    appid: your_wechat_appid
    secret: your_wechat_secret
    mchid: your_merchant_id
    mchSerialNo: your_merchant_serial_no
    privateKeyFilePath: path/to/your/apiclient_key.pem
    apiV3Key: your_api_v3_key
    weChatPayCertFilePath: path/to/your/wechatpay_cert.pem
    notifyUrl: your_notify_url
    refundNotifyUrl: your_refund_notify_url

